### ISSUE TITLE
DataGrid is displayed incorrect

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-ui#338]
Enviroment:
JMIX v.1.0.0-SNAPSHOT

TC:
1. Create new roject
2. Open 'UserBrowse' XML-descriptor
3. Add component 'DataGrid' into component hierarchy tree above existing GroupTable
4. Run app
5. Open User browser screen

AR:
components are displayed incorrect, button 'Settings' of DataGrid should not be into ButtonPanel of GroupTable:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/1fe44883-fab8-49c5-b4b4-06e39d828191)

**Comment by glebfox** [comment]
@owlet1997, I do wanga that DataGrid has auto-size. In this case, this visual issue can be ignored, because such UI components as DataGrid and Table supposed to have suitable sizes. Nevertheless, it seems that after updating to Vaadin 8.12.2 everything works like a charm:

<img width="873" alt="Screenshot 2021-03-31 at 13 13 23" src="https://user-images.githubusercontent.com/6077149/113120693-e72d9680-9222-11eb-9bff-3f8302c33fd1.png">

**Comment by owlet1997** [comment]
Cannot reproduce on JMIX v.1.0.0-SNAPSHOT
