### ISSUE TITLE
ExcelExportAction is broken

### ISSUE THREAD

**Issue by KartonDCP** [Haulmont/jmix-ui#371]
* Create new Jmix project
* add dependency to jmix-ui-export (`implementation 'io.jmix.ui:jmix-ui-export'`)
* create any BrowseScreen
* go to xml declaration and peek GroupTable's actions 
* add here  `<action id="anyName" type="excelExport">`
* open this screen :
* here is IllegalArgumentException: Unable to find action type: excelExport
![Снимок экрана (10)](https://user-images.githubusercontent.com/43281522/110535033-d06ab700-8130-11eb-8c97-275ef74bae7f.png)

**Comment by KartonDCP** [comment]
I did hardcore version link ExcelExportAction to the button instead of xml `<action id="anyName" type="excelExport">`
and i got NPE in getIcon method caused by `Icons icons` component was null (not injected by `@Autowired`)
So if facade and override it with  `public String getIcon() {return "";}` action will work

**Comment by Flaurite** [comment]
The problem occurs due to `io.jmix.ui:jmix-ui-export` dependency. 

I think, `io.jmix.ui:jmix-ui-export` usage is not recommended, because Auto Configuration may have conditional beans and you should manually add `UiExportConfiguration` to the app configuration like this:
```
@SpringBootApplication
@Import(UiExportConfiguration.class)
public class DemoAppApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoAppApplication.class, args);
    }
}
```
For `ui-export` module we have `io.jmix.ui:jmix-ui-export-starter` that will add `UiExportConfiguration` to the app context.
