### ISSUE TITLE
The DataGrid header is hidden when users reorder the columns (port to 1.0.x)

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-ui#687]
See https://github.com/haulmont/jmix-ui/issues/623

**Comment by konyashkina** [comment]
_Tested on_ 
Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3579-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Community Edition)

The issue is reproduced. 
![DataGrid-header-is-hidden](https://user-images.githubusercontent.com/85500330/136161741-b66d7df2-1f10-4b76-94ee-40bfbfe89642.png)

**Comment by glebfox** [comment]
@konyashkina did you refresh the browser without cache?

**Comment by konyashkina** [comment]
Tested. Verified.
The header is shown when user reorders the columns in DataGrid. 

![DataGrid-header-is-shown](https://user-images.githubusercontent.com/85500330/136165746-be594b55-2801-4b67-a39c-9c0844697a38.png)
